### ISSUE TITLE
AWS monitoring

### ISSUE THREAD

**Issue by acholyn** [UCL-ARC/museum_of_dreams#11]
set up 

- [x] cost alerts and 
- [x] downtime alerts
```[tasklist]
### Tasks
- [x] set up AWS slack notifications
- [x] rds slack notifs
- [x] ebs slack notifs
```
