### ISSUE TITLE
Update aesthetics

### ISSUE THREAD

**Issue by acholyn** [UCL-ARC/museum_of_dreams#76]
Maria has provided a logo which has a different colour scheme and would like this reflected in the rest of the website. They would also like to disable public viewing of the content - perhaps to be put behind a login check
```[tasklist]
### Tasks
- [x] add new logo
- [x] update colour scheme
- [x] reduce public visibility
- [x] add banner to say under construction on home page
```
