### ISSUE TITLE
enable selection from s3 images so they can be reused

### ISSUE THREAD

**Issue by acholyn** [UCL-ARC/museum_of_dreams#84]
Having a way to view items that have already been uploaded to the s3 bucket will limit duplicating items and taking up unnecessary space. It will also streamline the process since each researcher doesn't need a copy locally to use it.
```[tasklist]
### Tasks
- [x] enable for inline forms (Stills, Posters, etc)
- [x] enable for CKeditor
- [ ] demo for researchers so they know the different ways of accessing images
- [ ] add tests via cypress?
- [ ] add a filter for file type
```
